### ISSUE TITLE
When a user fills up the post with the onboarding message, the "Post" button must be always reachable, so the user can complete the action

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/web-extension#12]
Onboarding window is going on top of the button "Publish" 
![image](https://cloud.githubusercontent.com/assets/89555/21314094/532d2fd4-c5dc-11e6-96c9-611874350fdf.png)

**Comment by vrde** [comment]
# Beginners welcome!

This issue is almost easy to handle, and we can guide you through its resolution! Read the *description* and the *how to solve it* sections. If you wish to work on this issue, **please remember to add a comment

If you are **not** a beginner, take a look to [other issues](https://github.com/tracking-exposed/web-extension/issues), thanks!

# Description

When a user installs the extension for the first time, a message box appears. This is called *onboarding box*, it contains information on how to register on the service. If you are curious about the onboarding process, take a look to the source code of [`src/app.js`](https://github.com/tracking-exposed/web-extension/blob/v1.0.4/src/app.js), it's well documented and—hopefully—understandable.

![image](https://cloud.githubusercontent.com/assets/134680/21468015/5ec0ddea-ca01-11e6-8880-c841efca6206.png)

It's big on purpose. You cannot ignore it :stuck_out_tongue:. But you can minimize it anytime using the **Close box** button. If the user is on a not–so–big–screen, the *onboarding box* might cover the **post** button. Since the user is prompted to publish a post with specific content, the **post** button is crucial.

The solution is to **hide** the *onboarding box* when the user starts the interaction to *publish a new post*.

# How to solve it
My idea is to use the [`Mutation Observer API`](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) on the `#feedx_sprouts_container` in the user's newsfeed.

![image](https://cloud.githubusercontent.com/assets/134680/21468077/51d81614-ca03-11e6-9d46-94de8a173e30.png)

I did a small experiment and added a listener on the fly using the browser console.

```javascript
var target = document.getElementById('feedx_sprouts_container');
var observer = new MutationObserver(function(mutations) {
  mutations.forEach(function(mutation) {
    console.log(mutation);
  });    
});
var config = { attributes: true, childList: true, characterData: true, subtree: true };
observer.observe(target, config);
```

This code will basically log everything that happens to the `#feedx_sprouts_container`. A combination of those events can be used to close/show the *message box*.

If you are interested in solving this issue, we can start a discussion and I can add more details on how to solve it.

**Comment by Kashyap12** [comment]
Hi @vrde can I start on this?

**Comment by vrde** [comment]
Hey @Kashyap12, sure thing! Do you need any extra information?

**Comment by vecna** [comment]
Just a reminder, don't assume that `#feedx_sprouts_container` will always exists, because facebook can change it every time. so if you go for that option, try to see what happen in case the ID name change.

A different option, is using the css attribute `z-index` wisely, so if something get rendered on top, takes priority. Just I don't know if we can figure out proper logic of `z-index` assignment.

**Comment by vrde** [comment]
> Just a reminder, don't assume that #feedx_sprouts_container will always exists, because facebook can change it every time. so if you go for that option, try to see what happen in case the ID name change.

I think `#feedx_sprouts_container` will stay there for a while since it's not one of the generated class names you see usually in their DOM. Anyway we need a way to anchor events to some elements, and using class names that are "human readable" seems (IMO) the most reliable way. I'm not sure about alternatived :thinking: 

> A different option, is using the css attribute z-index wisely, so if something get rendered on top, takes priority. Just I don't know if we can figure out proper logic of z-index assignment.

Yep, this is another option. Initially I excluded it, but after some time (7 days) I think it's a simple and good option too. @Kashyap12 what do you think?
