### ISSUE TITLE
Make this addon compatible with Firefox

### ISSUE THREAD

**Issue by bakulf** [tracking-exposed/web-extension#53]
I haven't debugged it completely, but mainly the bug is in the management of Promise prototype of core-js. WebExtension APIs in Firefox are promise-based but core-js has its own implementation of Promise. This breaks everything. The solution is something like that:

```
diff --git a/src/app.js b/src/app.js
index 9eca865..00879f1 100644
--- a/src/app.js
+++ b/src/app.js
@@ -26,6 +26,8 @@ require('../styles/app.scss');
 // Install any necessary polyfills into global, such as es6, stage/3, stage/4, etc. as needed
 import 'core-js/es6';
 
+Promise = window.Promise;
+
 // Import the react toolkit.
 // Seems like importing 'react-dom' is not enough, we need to import 'react' as well.
 import React from 'react';
```

Or probably, better, don't include core-js/es6 because chrome and firefox are both es6.
I haven't checked if this breaks the addon for chrome.

I would like to thanks @rpl, who actually found the solution.

**Comment by vecna** [comment]
Thanks, I'll test it in the next days.

**Comment by vrde** [comment]
> WebExtension APIs in Firefox are promise-based but core-js has its own implementation of Promise. This breaks everything.

That's interesting, do you know if there is any open issue on `core-js` related to this bug?

> Or probably, better, don't include core-js/es6 because chrome and firefox are both es6.
:+1:

**Comment by rpl** [comment]
@vrde I consider it a Firefox bug that it should be fixed in the WebExtensions internals (I mean a library that redefines a native object should not be able to break the extension messaging APIs in a content script, especially by providing a very "not helpful" error message), and I'm going to look a bit deeper into it and file a bug on bugzilla.

Nevertheless, I was wondering why `"core-js/es6"` is redefining the `Promise` object instead of using the one provided natively, and I found these `"core-js"` issues that looks related:

- https://github.com/zloirock/core-js/issues/264
- https://github.com/zloirock/core-js/issues/140

**Comment by Mte90** [comment]
Any news for the support?

**Comment by vecna** [comment]
everybody was busy, but will completed soon.

**Comment by vecna** [comment]
PR in #55

**Comment by vecna** [comment]
stable and also the revision process is not accepted smoothly.
