### ISSUE TITLE
Reduce the size of the addon

### ISSUE THREAD

**Issue by bakulf** [tracking-exposed/web-extension#54]
Currently, the addon is ~2mb. A bit too much. Probably, removing react and webpack will help.
Personally, the complexity of this addon doesn't require such big frameworks.

**Comment by vecna** [comment]
I was thinking to the opposite: also embed d3.js, c3.js, moment.js, and jQuery. In this way, supporters with the plugin can just request the JSON data, and get rendered the visualizations from the add-on, instead of downloading all the requirements from the web.

**Comment by bakulf** [comment]
ContentScripts are embedded in the pages. This means that you force your 2mb of scripts for each facebook.com tab. The real point is: do you really need all those dependences? Remember: Less is more :)

**Comment by vrde** [comment]
> Currently, the addon is ~2mb. A bit too much. Probably, removing react and webpack will help.

React is not used in `app.js` (aka the script injected). Webpack is the tool we use to build the extension, so it's not responsible for the size.

The size of the extension (aka zip archive) in the store is [315KiB](https://chrome.google.com/webstore/detail/facebooktrackingexposed/fnknflppefckhjhecbfigfhlcbmcnmmi)

![image](https://user-images.githubusercontent.com/134680/27432542-ef63f526-5750-11e7-9786-6ccab31797f2.png)

The uncompressed extension size is the following:
```
 ~/r/t/web-extension git:(master) ➜ npm run build:dist

> tracking-exposed-extension@1.1.6 build:dist /home/vrde/repos/tracking-exposed/web-extension
> ./pack-extension.sh || true

NODE_ENV [production] Prod: true Devel:  false
Hash: 6722a14c95df32b6d231
Version: webpack 2.1.0-beta.17
Time: 48832ms
        Asset     Size  Chunks             Chunk Names
       app.js   344 kB       0  [emitted]  app
     popup.js   508 kB       1  [emitted]  popup
background.js   127 kB       2  [emitted]  background
   styles.css  1.51 kB       0  [emitted]  app
```

The code injected in the Facebook DOM is `app.js` and its size is 334KiB. `popup.js` and `background.js` AFAIK are loaded once, since you cannot have more than one instance per browser.

If you want to try to shrink more the script injected, you can try to do the following:
 - Check if all dependencies declared in `package.json` are used (it's really common to forget about some old ones).
- [Tree shaking](https://webpack.js.org/guides/tree-shaking/).

If you want to do more investigative work, you can try to add [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) and profile the bundle. I never had time to do it, but it should be fun! :dancer:
