### ISSUE TITLE
Support multiple Facebook users using the same browser

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#98]
# Problem

Multiple users might use the same browser to connect to Facebook. Currently, the extension is not aware of this, and might mess up with the data sent to the backend.

# Solution

Since only one Facebook session can be active at the same time, the extension should check who's the current user, and load/save the data using the user's ID as a prefix in `localStorage`.

# Deliverable

Update all operations to `localStorage` to use the user's ID as prefix.

**Comment by vecna** [comment]
Yes, that's the right approach. 
To be sure: it should be based only on the userId extracted from the cookie, rather than from anything parsed from the webpage.
Also, this implies:
- when no user is logged in, the #96 pop-up should say "please login on facebook."
- and open a new problem: when the pop-up is open, how can we make the user recognize who the cookie owner is? 

To test this, you should try to have the same browser to observe more than one login:
![image](https://user-images.githubusercontent.com/89555/70328127-9aa59700-1838-11ea-9cb6-637fbb8f690e.png)
